### ISSUE TITLE
git pull

### ISSUE THREAD

**Issue by baibhavkumarpoudel** [baibhavkumarpoudel/project3-frontend#2]
1. tried to git pull Front end but it gives me this error:

error: The following untracked working tree files would be overwritten by merge:
        package-lock.json
Please move or remove them before you merge.
Aborting
Updating ebcfb88..50c9c4c

2. Should I delete the package-lock.json file from my end then git pulling it again? Did not want to break anything so I just wanted to run it by.

**Comment by CRHarding** [comment]
Have you tried to git add . / git commit?

**Comment by CRHarding** [comment]
I would say try to add / commit what you have locally first, then try and pull. If that doesn't work you can always remove the package-lock.json but that should be a last resort.

**Comment by baibhavkumarpoudel** [comment]
Skyler has been working on front end, so should i git add. and commit then try git pulling front end?

**Comment by CRHarding** [comment]
Yep, give it a shot

**Comment by baibhavkumarpoudel** [comment]
It did work, but now from my side, my package-lock.json shows 6 errors. Skyler slacked me his package-lock.json file, would it be ok if i copy paste that on mine and git add and commit again?

**Comment by Skyvassa** [comment]
We're both experiencing issues with our respective sides of this project and uploads. I respect the Issue Ticket system but if we can speak with you it'd be appreciated for a moment.

**Comment by CRHarding** [comment]
I would recommend against copying and pasting a package.lock, instead is it giving you merge errors?

**Comment by baibhavkumarpoudel** [comment]
it says <<<<<HEAD (current change) ...

(Incoming change) 

it asks me to "Accept current change, Accept incoming change, accept both changes, compare changes"

**Comment by CRHarding** [comment]
Accept the current change on all of 'em and then add and commit.

**Comment by baibhavkumarpoudel** [comment]
I did that, but now the package-lock.json has a red error exclamation mark on the tab section..

**Comment by CRHarding** [comment]
What does a red error exclamation mark mean? Did you miss any of the current changes?

**Comment by baibhavkumarpoudel** [comment]
yea looking at the file that Skyler had sent, i dont see any axios on mine. I just dont want to add/commit i shouldnt be.
